[package]
name = "rustyfactory"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = {version = "0.33.0", features = ["default", "__screenshot"]}
egui_extras = { version = "0.33.0", features = ["default", "image"] }
env_logger = { version = "0.11.8", features = ["auto-color", "humantime"] }
